COLUMN_MAP = {
    "market_and_exchange_names": "Market Names",
    "report_date_as_yyyy_mm_dd": "Date",
    "open_interest_all": "Open Interest",
    "prod_merc_positions_long": "Producer/Merchant/Processor/User Long",
    "prod_merc_positions_short": "Producer/Merchant/Processor/User Short",
    "swap_positions_long_all": "Swap_Dealer_Long",
    "swap__positions_short_all": "Swap_Dealer_Short",
    "swap__positions_spread_all": "Swap_Dealer_Spread",
    "m_money_positions_long_all": "Managed_Money_Long",
    "m_money_positions_short_all": "Managed_Money_Short",
    "m_money_positions_spread": "Managed_Money_Spread",
    "other_rept_positions_long": "Other_Reportables_Long",
    "other_rept_positions_short": "Other_Reportables_Short",
    "other_rept_positions_spread": "Other_Reportables_Spread",
    "traders_tot_all": "Total_Traders",
    "traders_prod_merc_long_all": "Traders_Prod_Merc_Long",
    "traders_prod_merc_short_all": "Traders_Prod_Merc_Short",
    "traders_swap_long_all": "Traders_Swap_Long",
    "traders_swap_short_all": "Traders_Swap_Short",
    "traders_swap_spread_all": "Traders_Swap_Spread",
    "traders_m_money_long_all": "Traders_M_Money_Long",
    "traders_m_money_short_all": "Traders_M_Money_Short",
    "traders_m_money_spread_all": "Traders_M_Money_Spread",
    "traders_other_rept_long_all": "Traders_Other_Rept_Long",
    "traders_other_rept_short": "Traders_Other_Rept_Short",
    "traders_other_rept_spread": "Traders_Other_Rept_Spread"
}
